### ISSUE TITLE
Unable to run on Mac OS Sierra

### ISSUE THREAD

**Issue by mattbliss** [sieteunoseis/cucm-phone-inventory-tool#1]
I'm able to build using python3 setup.py py2app -A but then when I open the application I see the below error in console and then the application terminates.  I'm on python3.6 and py2app 0.13.

Detected missing constraints for <private>.  It cannot be placed because there are not enough constraints to fully define the size and origin. Add the missing constraints, or set translatesAutoresizingMaskIntoConstraints=YES and constraints will be generated for you. If this view is laid out manually on macOS 10.12 and later, you may choose to not call [super layout] from your override. Set a breakpoint on DETECTED_MISSING_CONSTRAINTS to debug. This error will only be logged once.

**Comment by sieteunoseis** [comment]
What version of Py2app are you using? I had to downgrade mine to 0.12 recently to get it to work.

**Comment by mattbliss** [comment]
When searching for the issue I was seeing I found the recommendation to downgrade to 0.12 as well but still have the same errors.  When compiling if I run -A it builds but fails as described above but if I run without -A I get an error starting with py2app (0.12) but is non descript to me.  I can try running on older Mac running Mavericks I think and do clean installs of packages.  Below is what errors I get without running with the -A flag.

Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    setup_requires=['py2app'],
  File "/Users/matthewbliss/cucm-phone-inventory-tool/myenv/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/site-packages/py2app/build_app.py", line 757, in run
    self._run()
  File "/usr/local/lib/python3.6/site-packages/py2app/build_app.py", line 967, in _run
    self.run_normal()
  File "/usr/local/lib/python3.6/site-packages/py2app/build_app.py", line 1055, in run_normal
    mf = self.get_modulefinder()
  File "/usr/local/lib/python3.6/site-packages/py2app/build_app.py", line 912, in get_modulefinder
    debug=debug,
  File "/usr/local/lib/python3.6/site-packages/modulegraph/find_modules.py", line 338, in find_modules
    find_needed_modules(mf, scripts, includes, packages)
  File "/usr/local/lib/python3.6/site-packages/modulegraph/find_modules.py", line 256, in find_needed_modules
    path = m.packagepath[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by sieteunoseis** [comment]
Can you try installing ttkthemes==1.5.2?

**Comment by mattbliss** [comment]
Got a bit further with that, thank you.

It was stopping on 
File "/usr/local/lib/python3.6/site-packages/PyQt5/uic/port_v2/ascii_upper.py", line 27, in <module>
    _ascii_trans_table = string.maketrans(string.ascii_lowercase,
AttributeError: module 'string' has no attribute 'maketrans'

so I modified ascii_upper.py 
from:
 _ascii_trans_table = string.maketrans(string.ascii_lowercase, string.ascii_uppercase)
to:
_ascii_trans_table = str.maketrans(string.ascii_lowercase, string.ascii_uppercase)

It now compiles but still when launched fails and then has open console / terminate.  Going through the long build now to see if there are any warnings / errors that may be causing it that didn't stop it from executing.

**Comment by mattbliss** [comment]
I moved to a almost fresh computer with no packages and started over. It compiles and i've started running the app/Contents/MacOS/app file to see where it's failing.  It's listing failing at     from suds.client import Client ModuleNotFoundError: No module named 'suds.client'.  Are you using suds-jurko?

pip3 list
Package     Version
----------- -------
altgraph    0.15   
client      0.0.1  
macholib    1.9    
modulegraph 0.16   
pip         10.0.1 
py2app      0.12   
setuptools  39.0.1 
suds-jurko  0.6    
ttkthemes   1.5.2  
wheel       0.31.0

**Comment by sieteunoseis** [comment]
Yep. need suds-jurko.

**Comment by sieteunoseis** [comment]
awesome. glad it worked out.
